/* Program Number: 41
   Student Name: Suhasini Madala; Register Number: BT2024043
   Date: 2-5-26
   Description: This program creates a message queue using msgget()
   and prints the key and message queue ID.
*/

#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/ipc.h>   /* For IPC_CREAT, ftok */
#include <sys/msg.h>   /* For msgget */

int main() {
    key_t key;
    int msgid;

    printf("===== Message Queue Creation =====\n\n");

    /* ftok() generates a unique IPC key from a pathname and project ID.
       The pathname must exist and be accessible.
       The project ID is a single character (only lower 8 bits used).
       
       This key is used to identify the IPC resource (message queue)
       so multiple processes can access the same queue. */
    key = ftok(".", 'A');  /* '.' = current directory, 'A' = project id */
    if (key == -1) {
        perror("ftok");
        exit(1);
    }
    printf("Generated IPC Key: %d (0x%x)\n", key, key);

    /* msgget() creates a new message queue or accesses an existing one.
       Arguments:
       - key: the IPC key generated by ftok
       - IPC_CREAT: create the queue if it doesn't exist
       - 0666: permissions (read/write for all)
       
       Returns: message queue ID (msqid), or -1 on error.
       The msqid is used in subsequent operations (msgsnd, msgrcv). */
    msgid = msgget(key, IPC_CREAT | 0666);
    if (msgid == -1) {
        perror("msgget");
        exit(1);
    }

    printf("Message Queue ID: %d\n\n", msgid);
    printf("Verify with: ipcs -q\n");
    printf("Remove with: ipcrm -q %d\n", msgid);

    return 0;
}
